// Code generated by entc, DO NOT EDIT.

package relative

import (
	"github.com/B6113759/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// RelativeName applies equality check predicate on the "relative_name" field. It's identical to RelativeNameEQ.
func RelativeName(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRelativeName), v))
	})
}

// RelativeNameEQ applies the EQ predicate on the "relative_name" field.
func RelativeNameEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRelativeName), v))
	})
}

// RelativeNameNEQ applies the NEQ predicate on the "relative_name" field.
func RelativeNameNEQ(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRelativeName), v))
	})
}

// RelativeNameIn applies the In predicate on the "relative_name" field.
func RelativeNameIn(vs ...string) predicate.Relative {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRelativeName), v...))
	})
}

// RelativeNameNotIn applies the NotIn predicate on the "relative_name" field.
func RelativeNameNotIn(vs ...string) predicate.Relative {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Relative(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRelativeName), v...))
	})
}

// RelativeNameGT applies the GT predicate on the "relative_name" field.
func RelativeNameGT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRelativeName), v))
	})
}

// RelativeNameGTE applies the GTE predicate on the "relative_name" field.
func RelativeNameGTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRelativeName), v))
	})
}

// RelativeNameLT applies the LT predicate on the "relative_name" field.
func RelativeNameLT(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRelativeName), v))
	})
}

// RelativeNameLTE applies the LTE predicate on the "relative_name" field.
func RelativeNameLTE(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRelativeName), v))
	})
}

// RelativeNameContains applies the Contains predicate on the "relative_name" field.
func RelativeNameContains(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRelativeName), v))
	})
}

// RelativeNameHasPrefix applies the HasPrefix predicate on the "relative_name" field.
func RelativeNameHasPrefix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRelativeName), v))
	})
}

// RelativeNameHasSuffix applies the HasSuffix predicate on the "relative_name" field.
func RelativeNameHasSuffix(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRelativeName), v))
	})
}

// RelativeNameEqualFold applies the EqualFold predicate on the "relative_name" field.
func RelativeNameEqualFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRelativeName), v))
	})
}

// RelativeNameContainsFold applies the ContainsFold predicate on the "relative_name" field.
func RelativeNameContainsFold(v string) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRelativeName), v))
	})
}

// HasDeceasedreceives applies the HasEdge predicate on the "deceasedreceives" edge.
func HasDeceasedreceives() predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DeceasedreceivesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeceasedreceivesTable, DeceasedreceivesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeceasedreceivesWith applies the HasEdge predicate on the "deceasedreceives" edge with a given conditions (other predicates).
func HasDeceasedreceivesWith(preds ...predicate.DeceasedReceive) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DeceasedreceivesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeceasedreceivesTable, DeceasedreceivesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Relative) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Relative) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Relative) predicate.Relative {
	return predicate.Relative(func(s *sql.Selector) {
		p(s.Not())
	})
}
