// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldUseremail holds the string denoting the useremail field in the database.
	FieldUseremail = "useremail"

	// EdgeDeceasedreceives holds the string denoting the deceasedreceives edge name in mutations.
	EdgeDeceasedreceives = "deceasedreceives"

	// Table holds the table name of the user in the database.
	Table = "users"
	// DeceasedreceivesTable is the table the holds the deceasedreceives relation/edge.
	DeceasedreceivesTable = "deceased_receives"
	// DeceasedreceivesInverseTable is the table name for the DeceasedReceive entity.
	// It exists in this package in order to avoid circular dependency with the "deceasedreceive" package.
	DeceasedreceivesInverseTable = "deceased_receives"
	// DeceasedreceivesColumn is the table column denoting the deceasedreceives relation/edge.
	DeceasedreceivesColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUserName,
	FieldUseremail,
}

var (
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// UseremailValidator is a validator for the "useremail" field. It is called by the builders before save.
	UseremailValidator func(string) error
)
