// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Coolroom is the predicate function for coolroom builders.
type Coolroom func(*sql.Selector)

// CoolroomType is the predicate function for coolroomtype builders.
type CoolroomType func(*sql.Selector)

// DeceasedReceive is the predicate function for deceasedreceive builders.
type DeceasedReceive func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Relative is the predicate function for relative builders.
type Relative func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
