// Code generated by entc, DO NOT EDIT.

package coolroom

import (
	"github.com/B6113759/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CoolroomName applies equality check predicate on the "coolroom_name" field. It's identical to CoolroomNameEQ.
func CoolroomName(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCoolroomName), v))
	})
}

// CoolroomCapacity applies equality check predicate on the "coolroom_capacity" field. It's identical to CoolroomCapacityEQ.
func CoolroomCapacity(v int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCoolroomCapacity), v))
	})
}

// CoolroomNameEQ applies the EQ predicate on the "coolroom_name" field.
func CoolroomNameEQ(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameNEQ applies the NEQ predicate on the "coolroom_name" field.
func CoolroomNameNEQ(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameIn applies the In predicate on the "coolroom_name" field.
func CoolroomNameIn(vs ...string) predicate.Coolroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Coolroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCoolroomName), v...))
	})
}

// CoolroomNameNotIn applies the NotIn predicate on the "coolroom_name" field.
func CoolroomNameNotIn(vs ...string) predicate.Coolroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Coolroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCoolroomName), v...))
	})
}

// CoolroomNameGT applies the GT predicate on the "coolroom_name" field.
func CoolroomNameGT(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameGTE applies the GTE predicate on the "coolroom_name" field.
func CoolroomNameGTE(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameLT applies the LT predicate on the "coolroom_name" field.
func CoolroomNameLT(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameLTE applies the LTE predicate on the "coolroom_name" field.
func CoolroomNameLTE(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameContains applies the Contains predicate on the "coolroom_name" field.
func CoolroomNameContains(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameHasPrefix applies the HasPrefix predicate on the "coolroom_name" field.
func CoolroomNameHasPrefix(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameHasSuffix applies the HasSuffix predicate on the "coolroom_name" field.
func CoolroomNameHasSuffix(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameEqualFold applies the EqualFold predicate on the "coolroom_name" field.
func CoolroomNameEqualFold(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCoolroomName), v))
	})
}

// CoolroomNameContainsFold applies the ContainsFold predicate on the "coolroom_name" field.
func CoolroomNameContainsFold(v string) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCoolroomName), v))
	})
}

// CoolroomCapacityEQ applies the EQ predicate on the "coolroom_capacity" field.
func CoolroomCapacityEQ(v int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCoolroomCapacity), v))
	})
}

// CoolroomCapacityNEQ applies the NEQ predicate on the "coolroom_capacity" field.
func CoolroomCapacityNEQ(v int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCoolroomCapacity), v))
	})
}

// CoolroomCapacityIn applies the In predicate on the "coolroom_capacity" field.
func CoolroomCapacityIn(vs ...int) predicate.Coolroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Coolroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCoolroomCapacity), v...))
	})
}

// CoolroomCapacityNotIn applies the NotIn predicate on the "coolroom_capacity" field.
func CoolroomCapacityNotIn(vs ...int) predicate.Coolroom {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Coolroom(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCoolroomCapacity), v...))
	})
}

// CoolroomCapacityGT applies the GT predicate on the "coolroom_capacity" field.
func CoolroomCapacityGT(v int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCoolroomCapacity), v))
	})
}

// CoolroomCapacityGTE applies the GTE predicate on the "coolroom_capacity" field.
func CoolroomCapacityGTE(v int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCoolroomCapacity), v))
	})
}

// CoolroomCapacityLT applies the LT predicate on the "coolroom_capacity" field.
func CoolroomCapacityLT(v int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCoolroomCapacity), v))
	})
}

// CoolroomCapacityLTE applies the LTE predicate on the "coolroom_capacity" field.
func CoolroomCapacityLTE(v int) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCoolroomCapacity), v))
	})
}

// HasDeceasedreceives applies the HasEdge predicate on the "deceasedreceives" edge.
func HasDeceasedreceives() predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DeceasedreceivesTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeceasedreceivesTable, DeceasedreceivesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeceasedreceivesWith applies the HasEdge predicate on the "deceasedreceives" edge with a given conditions (other predicates).
func HasDeceasedreceivesWith(preds ...predicate.DeceasedReceive) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DeceasedreceivesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeceasedreceivesTable, DeceasedreceivesColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCoolroomtype applies the HasEdge predicate on the "coolroomtype" edge.
func HasCoolroomtype() predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CoolroomtypeTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CoolroomtypeTable, CoolroomtypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoolroomtypeWith applies the HasEdge predicate on the "coolroomtype" edge with a given conditions (other predicates).
func HasCoolroomtypeWith(preds ...predicate.CoolroomType) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CoolroomtypeInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CoolroomtypeTable, CoolroomtypeColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Coolroom) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Coolroom) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Coolroom) predicate.Coolroom {
	return predicate.Coolroom(func(s *sql.Selector) {
		p(s.Not())
	})
}
