// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6113759/app/ent/coolroom"
	"github.com/B6113759/app/ent/coolroomtype"
	"github.com/B6113759/app/ent/deceasedreceive"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// CoolroomCreate is the builder for creating a Coolroom entity.
type CoolroomCreate struct {
	config
	mutation *CoolroomMutation
	hooks    []Hook
}

// SetCoolroomName sets the coolroom_name field.
func (cc *CoolroomCreate) SetCoolroomName(s string) *CoolroomCreate {
	cc.mutation.SetCoolroomName(s)
	return cc
}

// AddDeceasedreceifeIDs adds the deceasedreceives edge to DeceasedReceive by ids.
func (cc *CoolroomCreate) AddDeceasedreceifeIDs(ids ...int) *CoolroomCreate {
	cc.mutation.AddDeceasedreceifeIDs(ids...)
	return cc
}

// AddDeceasedreceives adds the deceasedreceives edges to DeceasedReceive.
func (cc *CoolroomCreate) AddDeceasedreceives(d ...*DeceasedReceive) *CoolroomCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return cc.AddDeceasedreceifeIDs(ids...)
}

// SetCoolroomtypeID sets the coolroomtype edge to CoolroomType by id.
func (cc *CoolroomCreate) SetCoolroomtypeID(id int) *CoolroomCreate {
	cc.mutation.SetCoolroomtypeID(id)
	return cc
}

// SetNillableCoolroomtypeID sets the coolroomtype edge to CoolroomType by id if the given value is not nil.
func (cc *CoolroomCreate) SetNillableCoolroomtypeID(id *int) *CoolroomCreate {
	if id != nil {
		cc = cc.SetCoolroomtypeID(*id)
	}
	return cc
}

// SetCoolroomtype sets the coolroomtype edge to CoolroomType.
func (cc *CoolroomCreate) SetCoolroomtype(c *CoolroomType) *CoolroomCreate {
	return cc.SetCoolroomtypeID(c.ID)
}

// Mutation returns the CoolroomMutation object of the builder.
func (cc *CoolroomCreate) Mutation() *CoolroomMutation {
	return cc.mutation
}

// Save creates the Coolroom in the database.
func (cc *CoolroomCreate) Save(ctx context.Context) (*Coolroom, error) {
	if _, ok := cc.mutation.CoolroomName(); !ok {
		return nil, &ValidationError{Name: "coolroom_name", err: errors.New("ent: missing required field \"coolroom_name\"")}
	}
	if v, ok := cc.mutation.CoolroomName(); ok {
		if err := coolroom.CoolroomNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "coolroom_name", err: fmt.Errorf("ent: validator failed for field \"coolroom_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Coolroom
	)
	if len(cc.hooks) == 0 {
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoolroomMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cc.mutation = mutation
			node, err = cc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			mut = cc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CoolroomCreate) SaveX(ctx context.Context) *Coolroom {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cc *CoolroomCreate) sqlSave(ctx context.Context) (*Coolroom, error) {
	c, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	c.ID = int(id)
	return c, nil
}

func (cc *CoolroomCreate) createSpec() (*Coolroom, *sqlgraph.CreateSpec) {
	var (
		c     = &Coolroom{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: coolroom.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: coolroom.FieldID,
			},
		}
	)
	if value, ok := cc.mutation.CoolroomName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coolroom.FieldCoolroomName,
		})
		c.CoolroomName = value
	}
	if nodes := cc.mutation.DeceasedreceivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   coolroom.DeceasedreceivesTable,
			Columns: []string{coolroom.DeceasedreceivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: deceasedreceive.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.CoolroomtypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coolroom.CoolroomtypeTable,
			Columns: []string{coolroom.CoolroomtypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coolroomtype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return c, _spec
}
