// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/B6113759/app/ent/deceasedreceive"
	"github.com/B6113759/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DeceasedReceiveDelete is the builder for deleting a DeceasedReceive entity.
type DeceasedReceiveDelete struct {
	config
	hooks      []Hook
	mutation   *DeceasedReceiveMutation
	predicates []predicate.DeceasedReceive
}

// Where adds a new predicate to the delete builder.
func (drd *DeceasedReceiveDelete) Where(ps ...predicate.DeceasedReceive) *DeceasedReceiveDelete {
	drd.predicates = append(drd.predicates, ps...)
	return drd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (drd *DeceasedReceiveDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(drd.hooks) == 0 {
		affected, err = drd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeceasedReceiveMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			drd.mutation = mutation
			affected, err = drd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(drd.hooks) - 1; i >= 0; i-- {
			mut = drd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, drd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (drd *DeceasedReceiveDelete) ExecX(ctx context.Context) int {
	n, err := drd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (drd *DeceasedReceiveDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: deceasedreceive.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: deceasedreceive.FieldID,
			},
		},
	}
	if ps := drd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, drd.driver, _spec)
}

// DeceasedReceiveDeleteOne is the builder for deleting a single DeceasedReceive entity.
type DeceasedReceiveDeleteOne struct {
	drd *DeceasedReceiveDelete
}

// Exec executes the deletion query.
func (drdo *DeceasedReceiveDeleteOne) Exec(ctx context.Context) error {
	n, err := drdo.drd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deceasedreceive.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (drdo *DeceasedReceiveDeleteOne) ExecX(ctx context.Context) {
	drdo.drd.ExecX(ctx)
}
