// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6113759/app/ent/deceasedreceive"
	"github.com/B6113759/app/ent/relative"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// RelativeCreate is the builder for creating a Relative entity.
type RelativeCreate struct {
	config
	mutation *RelativeMutation
	hooks    []Hook
}

// SetRelativeName sets the relative_name field.
func (rc *RelativeCreate) SetRelativeName(s string) *RelativeCreate {
	rc.mutation.SetRelativeName(s)
	return rc
}

// AddDeceasedreceifeIDs adds the deceasedreceives edge to DeceasedReceive by ids.
func (rc *RelativeCreate) AddDeceasedreceifeIDs(ids ...int) *RelativeCreate {
	rc.mutation.AddDeceasedreceifeIDs(ids...)
	return rc
}

// AddDeceasedreceives adds the deceasedreceives edges to DeceasedReceive.
func (rc *RelativeCreate) AddDeceasedreceives(d ...*DeceasedReceive) *RelativeCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return rc.AddDeceasedreceifeIDs(ids...)
}

// Mutation returns the RelativeMutation object of the builder.
func (rc *RelativeCreate) Mutation() *RelativeMutation {
	return rc.mutation
}

// Save creates the Relative in the database.
func (rc *RelativeCreate) Save(ctx context.Context) (*Relative, error) {
	if _, ok := rc.mutation.RelativeName(); !ok {
		return nil, &ValidationError{Name: "relative_name", err: errors.New("ent: missing required field \"relative_name\"")}
	}
	if v, ok := rc.mutation.RelativeName(); ok {
		if err := relative.RelativeNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "relative_name", err: fmt.Errorf("ent: validator failed for field \"relative_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Relative
	)
	if len(rc.hooks) == 0 {
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RelativeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rc.mutation = mutation
			node, err = rc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RelativeCreate) SaveX(ctx context.Context) *Relative {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rc *RelativeCreate) sqlSave(ctx context.Context) (*Relative, error) {
	r, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	r.ID = int(id)
	return r, nil
}

func (rc *RelativeCreate) createSpec() (*Relative, *sqlgraph.CreateSpec) {
	var (
		r     = &Relative{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: relative.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: relative.FieldID,
			},
		}
	)
	if value, ok := rc.mutation.RelativeName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: relative.FieldRelativeName,
		})
		r.RelativeName = value
	}
	if nodes := rc.mutation.DeceasedreceivesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   relative.DeceasedreceivesTable,
			Columns: []string{relative.DeceasedreceivesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: deceasedreceive.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return r, _spec
}
