// Code generated by entc, DO NOT EDIT.

package coolroomtype

const (
	// Label holds the string label denoting the coolroomtype type in the database.
	Label = "coolroom_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCoolroomtypeName holds the string denoting the coolroomtype_name field in the database.
	FieldCoolroomtypeName = "coolroomtype_name"

	// EdgeCoolrooms holds the string denoting the coolrooms edge name in mutations.
	EdgeCoolrooms = "coolrooms"

	// Table holds the table name of the coolroomtype in the database.
	Table = "coolroom_types"
	// CoolroomsTable is the table the holds the coolrooms relation/edge.
	CoolroomsTable = "coolrooms"
	// CoolroomsInverseTable is the table name for the Coolroom entity.
	// It exists in this package in order to avoid circular dependency with the "coolroom" package.
	CoolroomsInverseTable = "coolrooms"
	// CoolroomsColumn is the table column denoting the coolrooms relation/edge.
	CoolroomsColumn = "coolroomtype_id"
)

// Columns holds all SQL columns for coolroomtype fields.
var Columns = []string{
	FieldID,
	FieldCoolroomtypeName,
}

var (
	// CoolroomtypeNameValidator is a validator for the "coolroomtype_name" field. It is called by the builders before save.
	CoolroomtypeNameValidator func(string) error
)
