// Code generated by entc, DO NOT EDIT.

package coolroomtype

import (
	"github.com/B6113759/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CoolroomtypeName applies equality check predicate on the "coolroomtype_name" field. It's identical to CoolroomtypeNameEQ.
func CoolroomtypeName(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameEQ applies the EQ predicate on the "coolroomtype_name" field.
func CoolroomtypeNameEQ(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameNEQ applies the NEQ predicate on the "coolroomtype_name" field.
func CoolroomtypeNameNEQ(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameIn applies the In predicate on the "coolroomtype_name" field.
func CoolroomtypeNameIn(vs ...string) predicate.CoolroomType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CoolroomType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCoolroomtypeName), v...))
	})
}

// CoolroomtypeNameNotIn applies the NotIn predicate on the "coolroomtype_name" field.
func CoolroomtypeNameNotIn(vs ...string) predicate.CoolroomType {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.CoolroomType(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCoolroomtypeName), v...))
	})
}

// CoolroomtypeNameGT applies the GT predicate on the "coolroomtype_name" field.
func CoolroomtypeNameGT(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameGTE applies the GTE predicate on the "coolroomtype_name" field.
func CoolroomtypeNameGTE(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameLT applies the LT predicate on the "coolroomtype_name" field.
func CoolroomtypeNameLT(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameLTE applies the LTE predicate on the "coolroomtype_name" field.
func CoolroomtypeNameLTE(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameContains applies the Contains predicate on the "coolroomtype_name" field.
func CoolroomtypeNameContains(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameHasPrefix applies the HasPrefix predicate on the "coolroomtype_name" field.
func CoolroomtypeNameHasPrefix(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameHasSuffix applies the HasSuffix predicate on the "coolroomtype_name" field.
func CoolroomtypeNameHasSuffix(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameEqualFold applies the EqualFold predicate on the "coolroomtype_name" field.
func CoolroomtypeNameEqualFold(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCoolroomtypeName), v))
	})
}

// CoolroomtypeNameContainsFold applies the ContainsFold predicate on the "coolroomtype_name" field.
func CoolroomtypeNameContainsFold(v string) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCoolroomtypeName), v))
	})
}

// HasCoolrooms applies the HasEdge predicate on the "coolrooms" edge.
func HasCoolrooms() predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CoolroomsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CoolroomsTable, CoolroomsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCoolroomsWith applies the HasEdge predicate on the "coolrooms" edge with a given conditions (other predicates).
func HasCoolroomsWith(preds ...predicate.Coolroom) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(CoolroomsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CoolroomsTable, CoolroomsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.CoolroomType) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.CoolroomType) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CoolroomType) predicate.CoolroomType {
	return predicate.CoolroomType(func(s *sql.Selector) {
		p(s.Not())
	})
}
