/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCoolroomEdges,
    EntCoolroomEdgesFromJSON,
    EntCoolroomEdgesFromJSONTyped,
    EntCoolroomEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCoolroom
 */
export interface EntCoolroom {
    /**
     * CoolroomName holds the value of the "coolroom_name" field.
     * @type {string}
     * @memberof EntCoolroom
     */
    coolroomName?: string;
    /**
     * 
     * @type {EntCoolroomEdges}
     * @memberof EntCoolroom
     */
    edges?: EntCoolroomEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCoolroom
     */
    id?: number;
}

export function EntCoolroomFromJSON(json: any): EntCoolroom {
    return EntCoolroomFromJSONTyped(json, false);
}

export function EntCoolroomFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCoolroom {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coolroomName': !exists(json, 'coolroom_name') ? undefined : json['coolroom_name'],
        'edges': !exists(json, 'edges') ? undefined : EntCoolroomEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCoolroomToJSON(value?: EntCoolroom | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coolroom_name': value.coolroomName,
        'edges': EntCoolroomEdgesToJSON(value.edges),
        'id': value.id,
    };
}


