/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCoolroomTypeEdges,
    EntCoolroomTypeEdgesFromJSON,
    EntCoolroomTypeEdgesFromJSONTyped,
    EntCoolroomTypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCoolroomType
 */
export interface EntCoolroomType {
    /**
     * CoolroomtypeName holds the value of the "coolroomtype_name" field.
     * @type {string}
     * @memberof EntCoolroomType
     */
    coolroomtypeName?: string;
    /**
     * 
     * @type {EntCoolroomTypeEdges}
     * @memberof EntCoolroomType
     */
    edges?: EntCoolroomTypeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCoolroomType
     */
    id?: number;
}

export function EntCoolroomTypeFromJSON(json: any): EntCoolroomType {
    return EntCoolroomTypeFromJSONTyped(json, false);
}

export function EntCoolroomTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCoolroomType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coolroomtypeName': !exists(json, 'coolroomtype_name') ? undefined : json['coolroomtype_name'],
        'edges': !exists(json, 'edges') ? undefined : EntCoolroomTypeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCoolroomTypeToJSON(value?: EntCoolroomType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coolroomtype_name': value.coolroomtypeName,
        'edges': EntCoolroomTypeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


