/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDeceasedReceiveEdges,
    EntDeceasedReceiveEdgesFromJSON,
    EntDeceasedReceiveEdgesFromJSONTyped,
    EntDeceasedReceiveEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDeceasedReceive
 */
export interface EntDeceasedReceive {
    /**
     * DeathTime holds the value of the "death_time" field.
     * @type {string}
     * @memberof EntDeceasedReceive
     */
    deathTime?: string;
    /**
     * 
     * @type {EntDeceasedReceiveEdges}
     * @memberof EntDeceasedReceive
     */
    edges?: EntDeceasedReceiveEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDeceasedReceive
     */
    id?: number;
}

export function EntDeceasedReceiveFromJSON(json: any): EntDeceasedReceive {
    return EntDeceasedReceiveFromJSONTyped(json, false);
}

export function EntDeceasedReceiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDeceasedReceive {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deathTime': !exists(json, 'death_time') ? undefined : json['death_time'],
        'edges': !exists(json, 'edges') ? undefined : EntDeceasedReceiveEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntDeceasedReceiveToJSON(value?: EntDeceasedReceive | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'death_time': value.deathTime,
        'edges': EntDeceasedReceiveEdgesToJSON(value.edges),
        'id': value.id,
    };
}


