/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRelativeEdges,
    EntRelativeEdgesFromJSON,
    EntRelativeEdgesFromJSONTyped,
    EntRelativeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRelative
 */
export interface EntRelative {
    /**
     * 
     * @type {EntRelativeEdges}
     * @memberof EntRelative
     */
    edges?: EntRelativeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRelative
     */
    id?: number;
    /**
     * RelativeName holds the value of the "relative_name" field.
     * @type {string}
     * @memberof EntRelative
     */
    relativeName?: string;
}

export function EntRelativeFromJSON(json: any): EntRelative {
    return EntRelativeFromJSONTyped(json, false);
}

export function EntRelativeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRelative {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntRelativeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'relativeName': !exists(json, 'relative_name') ? undefined : json['relative_name'],
    };
}

export function EntRelativeToJSON(value?: EntRelative | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntRelativeEdgesToJSON(value.edges),
        'id': value.id,
        'relative_name': value.relativeName,
    };
}


