/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDeceasedReceive,
    EntDeceasedReceiveFromJSON,
    EntDeceasedReceiveFromJSONTyped,
    EntDeceasedReceiveToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRelativeEdges
 */
export interface EntRelativeEdges {
    /**
     * Deceasedreceives holds the value of the deceasedreceives edge.
     * @type {Array<EntDeceasedReceive>}
     * @memberof EntRelativeEdges
     */
    deceasedreceives?: Array<EntDeceasedReceive>;
}

export function EntRelativeEdgesFromJSON(json: any): EntRelativeEdges {
    return EntRelativeEdgesFromJSONTyped(json, false);
}

export function EntRelativeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRelativeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deceasedreceives': !exists(json, 'Deceasedreceives') ? undefined : ((json['Deceasedreceives'] as Array<any>).map(EntDeceasedReceiveFromJSON)),
    };
}

export function EntRelativeEdgesToJSON(value?: EntRelativeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deceasedreceives': value.deceasedreceives === undefined ? undefined : ((value.deceasedreceives as Array<any>).map(EntDeceasedReceiveToJSON)),
    };
}


